package dev.lyo.hortay.ui.theme

import androidx.compose.ui.graphics.Color

// Brand seed: Telegram-blue, modulated for M3 Expressive tonal palette.
val Seed = Color(0xFF2A8DEC)

// Light scheme (full M3 role coverage).
val LightPrimary = Color(0xFF0061A4)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F7)
val LightOnSecondaryContainer = Color(0xFF101C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF2DAFF)
val LightOnTertiaryContainer = Color(0xFF251431)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFAFCFF)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFAFCFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF4F6FA)
val LightSurfaceContainer = Color(0xFFEEF1F5)
val LightSurfaceContainerHigh = Color(0xFFE8EBEF)
val LightSurfaceContainerHighest = Color(0xFFE2E5E9)

// Dark scheme.
val DarkPrimary = Color(0xFF9DCAFF)
val DarkOnPrimary = Color(0xFF003259)
val DarkPrimaryContainer = Color(0xFF00497F)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkSecondaryContainer = Color(0xFF3B4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F7)
val DarkTertiary = Color(0xFFD7BEE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkTertiaryContainer = Color(0xFF523F5F)
val DarkOnTertiaryContainer = Color(0xFFF2DAFF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkBackground = Color(0xFF0E1116)
val DarkOnBackground = Color(0xFFE3E2E6)
val DarkSurface = Color(0xFF0E1116)
val DarkOnSurface = Color(0xFFE3E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkSurfaceContainerLowest = Color(0xFF090B0F)
val DarkSurfaceContainerLow = Color(0xFF161A1F)
val DarkSurfaceContainer = Color(0xFF1A1F25)
val DarkSurfaceContainerHigh = Color(0xFF252A31)
val DarkSurfaceContainerHighest = Color(0xFF30363D)
